# -*- coding: utf-8 -*-
"""Desafio2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WpOuJZT8LEEjUxOUV0T73_O6I8MrMge-
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

Graus = [20,23,24,21,28,27,33]
Dias = ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sabado']

data = {
    'Dias': Dias,
    'Graus': Graus
}
df = pd.DataFrame(data)

print(df.head(7))
print('-------------------------------------')
print(df.tail(7))
print('-------------------------------------')

x = df['Dias']
y = df['Graus']

plt.plot(x,y, label='Temperatura da semana')
plt.title('Temperatura da semana')
plt.xlabel('Dias')
plt.ylabel('Graus')
plt.legend('Temperatura')
plt.show()

